### ISSUE TITLE
Python 2 or 3?

### ISSUE THREAD

**Issue by rekado** [mirnylab/hiclib-legacy#1]
The README claims that this package will build with Python 3.3+, but there are a number of `print` statements that correspond to Python 2.  There are also `print()` calls that correspond to Python 3.

**Comment by mimakaev** [comment]
Last time I checked, the library run under python 3.x  - using recent (3.7) python. It can be run with python 2.7 in theory, but I haven't tested it in years. At some point all print calls were converted to print(), and python 2 compatibility was enforced using six print_function. If there are any stray python-2-style print statements left that are affecting any functionality, I will correct them. Other than that, the library is in maintenance only right now, as we all switched to cooler/cooltools/distiller.

**Comment by rekado** [comment]
The problem is that hiclib does not build with Python 3.  The build fails when it encounters one of the Python 2 style `print` statements.

I'm providing a hiclib package for GNU Guix and it is still used by some at our institute for legacy projects, even though most have moved on to cooler.  This is why I'm trying to get the last official version to build with Python 3.

**Comment by mimakaev** [comment]
Hi,

Can you provide the error log? I will take a look later today. Maybe the
migration to GitHub introduced some errors.

Max

**Comment by mimakaev** [comment]
I tested the library on the most recent conda (python 3.7), and it builds and installs well. The only file that contained old python2 print statement is domainSearch.py. It is a legacy file and is not imported by any other module in the library. I'm going to remove it. Hope it helps.

**Comment by rekado** [comment]
Thank you.  The build passes.
